- name: centralRouter | set centralRouter
  hosts: centralRouter
  become: true
  
  tasks:
    - name: stop ufw
      become: yes
      become_user: root
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt

    - name: install traceroute on ubuntu
      apt:
        name:
          - traceroute
        state: present
        update_cache: true

    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: disable default route & add default gateway
      template: 
        src: templates/centralRouter/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: add routes
      template: 
        src: templates/centralRouter/50-vagrant.yaml
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: netplan apply
      ansible.builtin.shell: netplan apply
      become: true
      
      
    
      
    

  
